/**
 * VISUAL FIXTURES — not FNX games.
 *
 * These exist only so layouts can be judged with realistic, colourful content while
 * the real catalogue is empty. They are flagged `isDemo`: never in the sitemap, never
 * indexed (detail pages are noindex, without JSON-LD), never playable, and never shown
 * once a production game exists or fixtures are off (see src/config/demo.ts and
 * src/lib/games/catalog.ts). Copy and facts below are placeholders, not product claims.
 *
 * Artwork lives in public/visual-fixtures/ and is generated by
 * scripts/visual-fixtures/render.mjs. Delete this folder and that one to remove them.
 */
import type { GameInput } from '@/config/schema/game.schema';

const base = { status: 'coming-soon', category: 'slot', featured: true, isDemo: true } as const;
const launch = { orientation: 'landscape', aspectRatio: '16/9', readySignal: false } as const;
const art = (slug: string) => ({
  thumbnail: `/visual-fixtures/games/${slug}.jpg`,
  hero: `/visual-fixtures/games/${slug}-hero.jpg`,
  heroMobile: `/visual-fixtures/games/${slug}.jpg`,
  screenshots: [`/visual-fixtures/games/${slug}-screen-1.jpg`, `/visual-fixtures/games/${slug}-screen-2.jpg`],
});

export const demoGames: GameInput[] = [
  {
    ...base,
    id: 'dragons-fortune',
    slug: 'dragons-fortune',
    title: 'Dragon’s Fortune',
    shortDescription: 'A gold dragon coils around an ember sun, guarding everything it has ever won.',
    description:
      'Beneath a sun the colour of embers, a dragon wraps itself around its hoard. Lanterns sway above the reels and every spin tightens the coil.\n\nFree spins open the hoard: the dragon unwinds, symbols land heavier and the reels slow just enough to let each win arrive.',
    order: 1,
    artwork: { ...art('dragons-fortune'), objectPosition: '62% 46%' },
    game: launch,
    info: { reels: 5, rows: 3, ways: 243, mechanics: ['Ways pays', 'Stacked wilds'], features: ['Free spins', 'Lantern respins'] },
    theme: { accent: '#ffcf7a', glow: '#e2402a', deep: '#1a0406' },
  },
  {
    ...base,
    id: 'mystic-tides',
    slug: 'mystic-tides',
    title: 'Mystic Tides',
    shortDescription: 'Moonlit water, drifting jellyfish and cascades that glow a little brighter each time.',
    description:
      'A calm indigo sea under a full moon, lit from below by drifting light. Wins wash away and new symbols fall into their place.\n\nCascades keep a session moving without rushing it — each chain a little brighter than the last.',
    order: 2,
    artwork: { ...art('mystic-tides'), objectPosition: '48% 42%' },
    game: launch,
    info: { reels: 6, rows: 4, ways: 4096, mechanics: ['Cascades', 'Ways pays'], features: ['Free spins', 'Rising multiplier'] },
    theme: { accent: '#cfd9ff', glow: '#6a3fe0', deep: '#070822' },
  },
  {
    ...base,
    id: 'temple-of-valor',
    slug: 'temple-of-valor',
    title: 'Temple of Valor',
    shortDescription: 'A jungle temple lit from within, holding its prizes in place.',
    description:
      'An old temple deep in the jungle, glowing from its highest step. Sun medallions that land stay where they are while the rest of the reels turn.\n\nHold & win builds slowly and visibly, so the moment the last position fills feels earned.',
    order: 3,
    artwork: { ...art('temple-of-valor'), objectPosition: '55% 48%' },
    game: launch,
    info: { reels: 5, rows: 3, paylines: 20, mechanics: ['Paylines', 'Sticky prizes'], features: ['Hold & win', 'Free spins'] },
    theme: { accent: '#ffe39a', glow: '#1fa56a', deep: '#03140c' },
  },
  {
    ...base,
    id: 'neon-heist',
    slug: 'neon-heist',
    title: 'Neon Heist',
    shortDescription: 'A vault of light under neon rain — crack it open one spin at a time.',
    description:
      'Rain streaks down a violet skyline while a vault diamond sits in the middle of the reels. Every near-miss lights another ring.\n\nExpanding wilds cut through the grid; land three vault symbols and the heist begins.',
    order: 4,
    artwork: { ...art('dragons-fortune'), objectPosition: '62% 46%' },
    game: launch,
    info: { reels: 5, rows: 4, ways: 1024, mechanics: ['Ways pays', 'Expanding wilds'], features: ['Vault free spins', 'Neon multipliers'] },
    theme: { accent: '#5ce1ff', glow: '#c84dff', deep: '#05010f' },
  },
  {
    ...base,
    id: 'golden-harbour',
    slug: 'golden-harbour',
    title: 'Golden Harbour',
    shortDescription: 'Dusk over a quiet harbour, with a lighthouse that pays when the tide turns.',
    description:
      'Warm light settles on the water as the lighthouse keeps time. Wins arrive in soft waves rather than sudden bursts.\n\nCollect harbour tokens across the session; fill the pier and a dusk bonus opens the board.',
    order: 5,
    artwork: { ...art('mystic-tides'), objectPosition: '48% 42%' },
    game: launch,
    info: { reels: 5, rows: 3, paylines: 25, mechanics: ['Paylines', 'Collect'], features: ['Dusk bonus', 'Lighthouse wilds'] },
    theme: { accent: '#f0bd72', glow: '#e07a3a', deep: '#0a1820' },
  },
  {
    ...base,
    category: 'instant',
    id: 'crystal-vault',
    slug: 'crystal-vault',
    title: 'Crystal Vault',
    shortDescription: 'Shatter ice, reveal prizes — an instant game of cold light and sharp edges.',
    description:
      'A vault of frozen glass waits under violet light. Each pick cracks another face until the chamber opens.\n\nPick three matching shards to cash out, or keep going for the deep vault.',
    order: 6,
    artwork: { ...art('temple-of-valor'), objectPosition: '55% 48%' },
    game: { orientation: 'portrait', aspectRatio: '9/16', readySignal: false },
    info: { mechanics: ['Pick'], features: ['Shard match', 'Deep vault'] },
    theme: { accent: '#d4e8ff', glow: '#9a68ff', deep: '#04060f' },
  },
];
