/**
 * VISUAL FIXTURES — not FNX games.
 *
 * These exist only so layouts can be judged with realistic, colourful content while
 * the real catalogue is empty. They are flagged `isDemo`: never in the sitemap, never
 * indexed (detail pages are noindex, without JSON-LD), never playable, and never shown
 * once a production game exists or fixtures are off (see src/config/demo.ts and
 * src/lib/games/catalog.ts). Copy and facts below are placeholders, not product claims.
 *
 * Artwork lives in public/visual-fixtures/ and is generated by
 * scripts/visual-fixtures/render.mjs. Delete this folder and that one to remove them.
 */
import type { GameInput } from '@/config/schema/game.schema';

const base = { status: 'coming-soon', category: 'slot', featured: true, isDemo: true } as const;
const launch = { orientation: 'landscape', aspectRatio: '16/9', readySignal: false } as const;
const art = (slug: string) => ({
  thumbnail: `/visual-fixtures/games/${slug}.jpg`,
  hero: `/visual-fixtures/games/${slug}-hero.jpg`,
  heroMobile: `/visual-fixtures/games/${slug}.jpg`,
  screenshots: [`/visual-fixtures/games/${slug}-screen-1.jpg`, `/visual-fixtures/games/${slug}-screen-2.jpg`],
});

export const demoGames: GameInput[] = [
  {
    ...base,
    id: 'dragons-fortune',
    slug: 'dragons-fortune',
    title: 'Dragon’s Fortune',
    shortDescription: 'A gold dragon coils around an ember sun, guarding everything it has ever won.',
    description:
      'Beneath a sun the colour of embers, a dragon wraps itself around its hoard. Lanterns sway above the reels and every spin tightens the coil.\n\nFree spins open the hoard: the dragon unwinds, symbols land heavier and the reels slow just enough to let each win arrive.',
    order: 1,
    artwork: art('dragons-fortune'),
    game: launch,
    info: { reels: 5, rows: 3, ways: 243, mechanics: ['Ways pays', 'Stacked wilds'], features: ['Free spins', 'Lantern respins'] },
    theme: { accent: '#ffcf7a', glow: '#e2402a', deep: '#1a0406' },
  },
  {
    ...base,
    id: 'mystic-tides',
    slug: 'mystic-tides',
    title: 'Mystic Tides',
    shortDescription: 'Moonlit water, drifting jellyfish and cascades that glow a little brighter each time.',
    description:
      'A calm indigo sea under a full moon, lit from below by drifting light. Wins wash away and new symbols fall into their place.\n\nCascades keep a session moving without rushing it — each chain a little brighter than the last.',
    order: 2,
    artwork: art('mystic-tides'),
    game: launch,
    info: { reels: 6, rows: 4, ways: 4096, mechanics: ['Cascades', 'Ways pays'], features: ['Free spins', 'Rising multiplier'] },
    theme: { accent: '#cfd9ff', glow: '#6a3fe0', deep: '#070822' },
  },
  {
    ...base,
    id: 'temple-of-valor',
    slug: 'temple-of-valor',
    title: 'Temple of Valor',
    shortDescription: 'A jungle temple lit from within, holding its prizes in place.',
    description:
      'An old temple deep in the jungle, glowing from its highest step. Sun medallions that land stay where they are while the rest of the reels turn.\n\nHold & win builds slowly and visibly, so the moment the last position fills feels earned.',
    order: 3,
    artwork: art('temple-of-valor'),
    game: launch,
    info: { reels: 5, rows: 3, paylines: 20, mechanics: ['Paylines', 'Sticky prizes'], features: ['Hold & win', 'Free spins'] },
    theme: { accent: '#ffe39a', glow: '#1fa56a', deep: '#03140c' },
  },
];
